version: 2

models:
  - name: heap_events
    
    columns:
        - name: event_id
          tests:
              - not_null
    tests:
        - unique:
            column_name: "concat(event_id, session_id, event_table_name)"
              
  - name: heap_sessions
    
    columns:
        - name: session_id
          tests:
              - unique
              - not_null
              
  - name: heap_users
    
    columns:
        - name: user_id
          tests:
              - unique
              - not_null